Repository Lucaslab-Berkeley/Leopard-EM, pull requests merged in 2025-07, with the labels that each got.

#61 Make position reference `"top-left"` consistent between the extracted image boxes and statistics
  src/leopard_em/pydantic_models/data_structures/particle_stack.py
Labels: bugfix

#59 Add back batched cross-correlation for `refine_template` program
  docs/programs/refine_template.md
  src/leopard_em/backend/core_match_template.py
  src/leopard_em/backend/core_refine_template.py
  src/leopard_em/backend/cross_correlation.py
  src/leopard_em/backend/utils.py
  src/leopard_em/pydantic_models/data_structures/particle_stack.py
  src/leopard_em/pydantic_models/managers/constrained_search_manager.py
  src/leopard_em/pydantic_models/managers/refine_template_manager.py
  src/leopard_em/pydantic_models/utils.py
  tests/pydantic_models/test_particle_stack.py
  tests/self_consistency/test_backend_cross_correlate.py
  tests/utils/test_crop_extraction.py
Labels: enhancement, bugfix

#67 Bugfix: Projection normalization sometimes returns NaN due to zero variance
  src/leopard_em/backend/core_match_template.py
  src/leopard_em/backend/utils.py
Labels: bugfix

#68 Sync minor test and linting updates upstream
  src/leopard_em/utils/fourier_slice.py
  tests/self_consistency/test_backend_cross_correlate.py
  tests/utils/test_crop_extraction.py
Labels: organization
