Repository Lucaslab-Berkeley/Leopard-EM, pull requests merged in 2025-05, with the labels that each got.

#38 fix: updates for new fourier-slice version
  pyproject.toml
  src/leopard_em/utils/fourier_slice.py
Labels: bug

#36 Fixed normalization for non-square images
  src/leopard_em/backend/utils.py
Labels: bug

#22 Improving documentation for implemented programs
  .github/ISSUE_TEMPLTE/bug_report.md
  README.md
  docs/contributing.md
  docs/data_formats.md
  docs/examples/basic_configuration.ipynb
  docs/examples/match_template_manager_example.yaml
  docs/index.md
  docs/programs/constrained_search.md
  docs/programs/match_template.md
  docs/programs/optimize_template.md
  docs/programs/overview.md
  docs/programs/refine_template.md
  mkdocs.yml
  programs/constrained_search/constrained_search_example_config.yaml
  programs/match_template/match_template_example_config.yaml
  programs/match_template/run_match_template.py
  pyproject.toml
  src/leopard_em/pydantic_models/config/orientation_search.py
  src/leopard_em/pydantic_models/managers/constrained_search_manager.py
Labels: documentation, help wanted

#35 feat: add functions for GEV fitting
  src/leopard_em/analysis/gev_fit_metric.py
Labels: enhancement

#43 Automatic Python API generation for package
  .gitignore
  .pre-commit-config.yaml
  docs/contributing.md
  docs/examples/01_basic_configuration.ipynb
  docs/examples/02_extract_peak_info.ipynb
  docs/examples/03_compare_scoring_metrics.ipynb
  docs/examples/README.md
  docs/index.md
  docs/programs/overview.md
  examples/02-extract_peak_info.ipynb
  mkdocs.yml
  programs/constrained_search/run_constrained_search.py
  programs/optimize_b_factor.py
  programs/optimize_template/run_optimize_template.py
  pyproject.toml
  src/leopard_em/analysis/gev_fit_metric.py
  src/leopard_em/backend/core_match_template.py
  src/leopard_em/backend/utils.py
  src/leopard_em/pydantic_models/data_structures/particle_stack.py
  src/leopard_em/utils/cross_correlation.py
  src/leopard_em/utils/fourier_slice.py
Labels: documentation
