Repository Lucaslab-Berkeley/Leopard-EM, pull requests merged in 2025-03, with the labels that each got.

#17 Cast Pandas Series object to NumPy array before image extraction
  src/leopard_em/pydantic_models/particle_stack.py
Labels: bug

#14 Update match_template_example_config.yaml
  README.md
  match_template_example_config.yaml
Labels: bug, documentation

#23 README documentation links and example scripts
  README.md
  src/programs/match_template.py
  src/programs/refine_template.py
Labels: documentation
